[api]
port = 3000

[api.logger]
format = "[${ip}]:${port} ${status} - ${method} ${path}\n"
time_format = "02-Jan-2006 15:04:05"
timezone = "America/New_York"

[api.auth]
header_key = "header:Authorization"
header_prefix = "Bearer"

[api.cors]
allow_origins = ["http://localhost:3000, https://api.suggestions.gg, https://suggestions.gg, https://suggestionsvoting.ngrok.io"]
allow_headers = ["Origin, Content-Type, Accept, Authorization, User-Agent"]

[services]

[services.topgg]
id = 0
short_name = "topgg"
long_name = "Top.gg"
url = "https://top.gg"
get_stats_url = "https://top.gg/api/bots/474051954998509571/stats"
post_stats_url = "https://top.gg/api/bots/474051954998509571/stats"
accessor = "server_count"
key = "server_count"
enabled = true

[services.botsgg]
id = 1
short_name = "botsgg"
long_name = "Discord Bots"
url = "https://discord.bots.gg"
get_stats_url = "https://discord.bots.gg/api/v1/bots/474051954998509571"
post_stats_url = "https://discord.bots.gg/api/v1/bots/474051954998509571/stats"
accessor = "guildCount"
key = "guildCount"
enabled = true

[services.dlspace]
id = 2
short_name = "dlspace"
long_name = "discordlist.space"
url = "https://discordlist.space"
get_stats_url = "https://api.discordlist.space/v2/bots/474051954998509571"
post_stats_url = "https://api.discordlist.space/v2/bots/474051954998509571"
accessor = "serverCount"
key = "serverCount"
enabled = true

[services.dbl]
id = 3
short_name = "dbl"
long_name = "Discord Bot List"
url = "https://discordbotlist.com"
get_stats_url = "https://discordbotlist.com/api/v1/bots/474051954998509571"
post_stats_url = "https://discordbotlist.com/api/v1/bots/474051954998509571/stats"
accessor = "stats.guilds"
key = "guilds"
enabled = true

[services.discords]
id = 4
short_name = "discords"
long_name = "Discords.com"
url = "https://discords.com"
get_stats_url = "https://discords.com/bots/api/bot/474051954998509571"
post_stats_url = "https://discords.com/bots/api/bot/474051954998509571"
accessor = "server_count"
key = "server_count"
enabled = true